### PR TITLE
CRLF conversion (fixes #9)

### LINKED ISSUE #9: Multiline strings on Windows end up with Windows line endings
If I have a string constant like

```
multiline :: String
multiline = [i|line 1
line 2
line 3|]
```

then it ends up having `\r\n` line endings:

```
-> multiline
"line 1\r\nline 2\r\nline 3"
```

This is a bit surprising and probably the wrong thing to do given that almost all Haskell libraries convert to normal `\n` endings when dealing with Windows (like `readFile` etc.).

In my case it causes confusion in tests, for example:

```
multilineConstant <- [i|
...
|]

unitTests = testSpec "(checked by Hspec)" $ do
  it "checks some output is valid" $ do
    result <- doSomething
    -- when everything else behaves properly, result has \n newlines but multilineConstant has \r\n
    result `shouldBe` multilineConstant 
```

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
@thomasjm I think this will fix the issue, but I didn't test on Windows.  Can you try?

**Comment by sol** [comment]
BTW, please ignore the build failure, that's a different issue (travis apparently does not provide `happy` anymore).

**Comment by thomasjm** [comment]
Thanks for the quick fix!

So the plot thickened slightly -- it turns out issue #9 only arises in certain situations. When I created a new stack project to test this, I didn't see the CRLFs. It turns out that enabling the `CPP` language extension makes issue #9 happen. I hadn't noticed that before because `CPP` is often enabled in my code when I'm doing Windows-related stuff. 

Also, there is some as-yet-unidentified factor that makes issue #9 arise in my main project sometimes, even when `CPP` is not present, so I don't totally understand when it happens.

Anyway, your fix appears to work in all situations I can find.

One possible concern with the fix is that you seem to be indiscriminately replacing all `\r\n` with `\n` -- what if someone deliberately types a `\r\n` in their quasiquote? It seems best if you can ensure you only modify newlines in the actual source file. This is still a big improvement though.

**Comment by sol** [comment]
> When I created a new stack project to test this, I didn't see the CRLFs.

Are you using `stack init` or something here?  This might just be a "bug" in `stack`.  The generated files may just be missing CRLF line endings (you can try to verify this with e.g. `:set ff` in `vim` or with `file`).

> One possible concern with the fix is that you seem to be indiscriminately replacing all `\r\n` with `\n` -- what if someone deliberately types a `\r\n` in their quasiquote? It seems best if you can ensure you only modify newlines in the actual source file.

I think this is what we already get.  We do the replacement before we decode any `\`-escape sequences.  So for e.g. `[i|foo\r\nbar|]` CRLF should be retained.  Is this what you meant?

**Comment by sol** [comment]
@snoyberg from what @thomasjm observed, `stack init` does not produce CRLF line endings on Windows.

The way I deal with this kind of situations by now is to leave the handle in text mode and use `hSetEncoding` to produce UTF8.  That way you get both, newline conversion and UTF8 (see e.g. https://github.com/NixOS/cabal2nix/commit/38db587a59a401ff88fec7f21fac00d93f7c12c2, I assume you could also use `text` based IO).

**Pull request closed without merging**
